<?php
/**
 * NetworksnetworkIdgroupPoliciesContentFiltering
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 July, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * NetworksnetworkIdgroupPoliciesContentFiltering Class Doc Comment
 *
 * @category Class
 * @description The content filtering settings for your group policy
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NetworksnetworkIdgroupPoliciesContentFiltering implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'networksnetworkIdgroupPolicies_contentFiltering';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'allowed_url_patterns' => '\Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns',
        'blocked_url_patterns' => '\Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns',
        'blocked_url_categories' => '\Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'allowed_url_patterns' => null,
        'blocked_url_patterns' => null,
        'blocked_url_categories' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allowed_url_patterns' => 'allowedUrlPatterns',
        'blocked_url_patterns' => 'blockedUrlPatterns',
        'blocked_url_categories' => 'blockedUrlCategories'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allowed_url_patterns' => 'setAllowedUrlPatterns',
        'blocked_url_patterns' => 'setBlockedUrlPatterns',
        'blocked_url_categories' => 'setBlockedUrlCategories'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allowed_url_patterns' => 'getAllowedUrlPatterns',
        'blocked_url_patterns' => 'getBlockedUrlPatterns',
        'blocked_url_categories' => 'getBlockedUrlCategories'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['allowed_url_patterns'] = isset($data['allowed_url_patterns']) ? $data['allowed_url_patterns'] : null;
        $this->container['blocked_url_patterns'] = isset($data['blocked_url_patterns']) ? $data['blocked_url_patterns'] : null;
        $this->container['blocked_url_categories'] = isset($data['blocked_url_categories']) ? $data['blocked_url_categories'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allowed_url_patterns
     *
     * @return \Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns
     */
    public function getAllowedUrlPatterns()
    {
        return $this->container['allowed_url_patterns'];
    }

    /**
     * Sets allowed_url_patterns
     *
     * @param \Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns $allowed_url_patterns allowed_url_patterns
     *
     * @return $this
     */
    public function setAllowedUrlPatterns($allowed_url_patterns)
    {
        $this->container['allowed_url_patterns'] = $allowed_url_patterns;

        return $this;
    }

    /**
     * Gets blocked_url_patterns
     *
     * @return \Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns
     */
    public function getBlockedUrlPatterns()
    {
        return $this->container['blocked_url_patterns'];
    }

    /**
     * Sets blocked_url_patterns
     *
     * @param \Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns $blocked_url_patterns blocked_url_patterns
     *
     * @return $this
     */
    public function setBlockedUrlPatterns($blocked_url_patterns)
    {
        $this->container['blocked_url_patterns'] = $blocked_url_patterns;

        return $this;
    }

    /**
     * Gets blocked_url_categories
     *
     * @return \Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories
     */
    public function getBlockedUrlCategories()
    {
        return $this->container['blocked_url_categories'];
    }

    /**
     * Sets blocked_url_categories
     *
     * @param \Swagger\Client\Model\NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories $blocked_url_categories blocked_url_categories
     *
     * @return $this
     */
    public function setBlockedUrlCategories($blocked_url_categories)
    {
        $this->container['blocked_url_categories'] = $blocked_url_categories;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


