<?php
/**
 * CreateNetworkFloorPlanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 July, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateNetworkFloorPlanTest Class Doc Comment
 *
 * @category    Class
 * @description CreateNetworkFloorPlan
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateNetworkFloorPlanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateNetworkFloorPlan"
     */
    public function testCreateNetworkFloorPlan()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "center"
     */
    public function testPropertyCenter()
    {
    }

    /**
     * Test attribute "bottom_left_corner"
     */
    public function testPropertyBottomLeftCorner()
    {
    }

    /**
     * Test attribute "bottom_right_corner"
     */
    public function testPropertyBottomRightCorner()
    {
    }

    /**
     * Test attribute "top_left_corner"
     */
    public function testPropertyTopLeftCorner()
    {
    }

    /**
     * Test attribute "top_right_corner"
     */
    public function testPropertyTopRightCorner()
    {
    }

    /**
     * Test attribute "image_contents"
     */
    public function testPropertyImageContents()
    {
    }
}
