<?php
/**
 * DevicesserialmanagementInterfaceWan1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 27 April, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.0.0-streaming
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DevicesserialmanagementInterfaceWan1Test Class Doc Comment
 *
 * @category    Class
 * @description WAN 1 settings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DevicesserialmanagementInterfaceWan1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DevicesserialmanagementInterfaceWan1"
     */
    public function testDevicesserialmanagementInterfaceWan1()
    {
    }

    /**
     * Test attribute "wan_enabled"
     */
    public function testPropertyWanEnabled()
    {
    }

    /**
     * Test attribute "using_static_ip"
     */
    public function testPropertyUsingStaticIp()
    {
    }

    /**
     * Test attribute "static_ip"
     */
    public function testPropertyStaticIp()
    {
    }

    /**
     * Test attribute "static_gateway_ip"
     */
    public function testPropertyStaticGatewayIp()
    {
    }

    /**
     * Test attribute "static_subnet_mask"
     */
    public function testPropertyStaticSubnetMask()
    {
    }

    /**
     * Test attribute "static_dns"
     */
    public function testPropertyStaticDns()
    {
    }

    /**
     * Test attribute "vlan"
     */
    public function testPropertyVlan()
    {
    }
}
