<?php
/**
 * UpdateNetworkSwitchRoutingOspfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 27 April, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.0.0-streaming
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UpdateNetworkSwitchRoutingOspfTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateNetworkSwitchRoutingOspf
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateNetworkSwitchRoutingOspfTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateNetworkSwitchRoutingOspf"
     */
    public function testUpdateNetworkSwitchRoutingOspf()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "hello_timer_in_seconds"
     */
    public function testPropertyHelloTimerInSeconds()
    {
    }

    /**
     * Test attribute "dead_timer_in_seconds"
     */
    public function testPropertyDeadTimerInSeconds()
    {
    }

    /**
     * Test attribute "areas"
     */
    public function testPropertyAreas()
    {
    }

    /**
     * Test attribute "md5_authentication_enabled"
     */
    public function testPropertyMd5AuthenticationEnabled()
    {
    }

    /**
     * Test attribute "md5_authentication_key"
     */
    public function testPropertyMd5AuthenticationKey()
    {
    }
}
