<?php
/**
 * AccessPoliciesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 27 April, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.0.0-streaming
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccessPoliciesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccessPoliciesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNetworkSwitchAccessPolicy
     *
     * Create an access policy for a switch network.
     *
     */
    public function testCreateNetworkSwitchAccessPolicy()
    {
    }

    /**
     * Test case for deleteNetworkSwitchAccessPolicy
     *
     * Delete an access policy for a switch network.
     *
     */
    public function testDeleteNetworkSwitchAccessPolicy()
    {
    }

    /**
     * Test case for getNetworkSwitchAccessPolicies
     *
     * List the access policies for a switch network.
     *
     */
    public function testGetNetworkSwitchAccessPolicies()
    {
    }

    /**
     * Test case for getNetworkSwitchAccessPolicy
     *
     * Return a specific access policy for a switch network.
     *
     */
    public function testGetNetworkSwitchAccessPolicy()
    {
    }

    /**
     * Test case for updateNetworkSwitchAccessPolicy
     *
     * Update an access policy for a switch network.
     *
     */
    public function testUpdateNetworkSwitchAccessPolicy()
    {
    }
}
