<?php
/**
 * ApplianceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 July, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ApplianceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplianceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNetworkApplianceStaticRoute
     *
     * Add a static route for an MX or teleworker network.
     *
     */
    public function testCreateNetworkApplianceStaticRoute()
    {
    }

    /**
     * Test case for createNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Add a custom performance class for an MX network.
     *
     */
    public function testCreateNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for createNetworkApplianceVlan
     *
     * Add a VLAN.
     *
     */
    public function testCreateNetworkApplianceVlan()
    {
    }

    /**
     * Test case for deleteNetworkApplianceStaticRoute
     *
     * Delete a static route from an MX or teleworker network.
     *
     */
    public function testDeleteNetworkApplianceStaticRoute()
    {
    }

    /**
     * Test case for deleteNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Delete a custom performance class from an MX network.
     *
     */
    public function testDeleteNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for deleteNetworkApplianceVlan
     *
     * Delete a VLAN from a network.
     *
     */
    public function testDeleteNetworkApplianceVlan()
    {
    }

    /**
     * Test case for getDeviceApplianceDhcpSubnets
     *
     * Return the DHCP subnet information for an appliance.
     *
     */
    public function testGetDeviceApplianceDhcpSubnets()
    {
    }

    /**
     * Test case for getDeviceAppliancePerformance
     *
     * Return the performance score for a single MX.
     *
     */
    public function testGetDeviceAppliancePerformance()
    {
    }

    /**
     * Test case for getNetworkApplianceClientSecurityEvents
     *
     * List the security events for a client.
     *
     */
    public function testGetNetworkApplianceClientSecurityEvents()
    {
    }

    /**
     * Test case for getNetworkApplianceConnectivityMonitoringDestinations
     *
     * Return the connectivity testing destinations for an MX network.
     *
     */
    public function testGetNetworkApplianceConnectivityMonitoringDestinations()
    {
    }

    /**
     * Test case for getNetworkApplianceContentFiltering
     *
     * Return the content filtering settings for an MX network.
     *
     */
    public function testGetNetworkApplianceContentFiltering()
    {
    }

    /**
     * Test case for getNetworkApplianceContentFilteringCategories
     *
     * List all available content filtering categories for an MX network.
     *
     */
    public function testGetNetworkApplianceContentFilteringCategories()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallCellularFirewallRules
     *
     * Return the cellular firewall rules for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallCellularFirewallRules()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallFirewalledService
     *
     * Return the accessibility settings of the given service ('ICMP', 'web', or 'SNMP').
     *
     */
    public function testGetNetworkApplianceFirewallFirewalledService()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallFirewalledServices
     *
     * List the appliance services and their accessibility rules.
     *
     */
    public function testGetNetworkApplianceFirewallFirewalledServices()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallInboundFirewallRules
     *
     * Return the inbound firewall rules for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallInboundFirewallRules()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallL3FirewallRules
     *
     * Return the L3 firewall rules for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallL3FirewallRules()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallL7FirewallRules
     *
     * List the MX L7 firewall rules for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallL7FirewallRules()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallL7FirewallRulesApplicationCategories
     *
     * Return the L7 firewall application categories and their associated applications for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallL7FirewallRulesApplicationCategories()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallOneToManyNatRules
     *
     * Return the 1:Many NAT mapping rules for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallOneToManyNatRules()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallOneToOneNatRules
     *
     * Return the 1:1 NAT mapping rules for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallOneToOneNatRules()
    {
    }

    /**
     * Test case for getNetworkApplianceFirewallPortForwardingRules
     *
     * Return the port forwarding rules for an MX network.
     *
     */
    public function testGetNetworkApplianceFirewallPortForwardingRules()
    {
    }

    /**
     * Test case for getNetworkAppliancePort
     *
     * Return per-port VLAN settings for a single MX port..
     *
     */
    public function testGetNetworkAppliancePort()
    {
    }

    /**
     * Test case for getNetworkAppliancePorts
     *
     * List per-port VLAN settings for all ports of a MX..
     *
     */
    public function testGetNetworkAppliancePorts()
    {
    }

    /**
     * Test case for getNetworkApplianceSecurityEvents
     *
     * List the security events for a network.
     *
     */
    public function testGetNetworkApplianceSecurityEvents()
    {
    }

    /**
     * Test case for getNetworkApplianceSecurityIntrusion
     *
     * Returns all supported intrusion settings for an MX network.
     *
     */
    public function testGetNetworkApplianceSecurityIntrusion()
    {
    }

    /**
     * Test case for getNetworkApplianceSecurityMalware
     *
     * Returns all supported malware settings for an MX network.
     *
     */
    public function testGetNetworkApplianceSecurityMalware()
    {
    }

    /**
     * Test case for getNetworkApplianceSettings
     *
     * Return the appliance settings for a network.
     *
     */
    public function testGetNetworkApplianceSettings()
    {
    }

    /**
     * Test case for getNetworkApplianceSingleLan
     *
     * Return single LAN configuration.
     *
     */
    public function testGetNetworkApplianceSingleLan()
    {
    }

    /**
     * Test case for getNetworkApplianceStaticRoute
     *
     * Return a static route for an MX or teleworker network.
     *
     */
    public function testGetNetworkApplianceStaticRoute()
    {
    }

    /**
     * Test case for getNetworkApplianceStaticRoutes
     *
     * List the static routes for an MX or teleworker network.
     *
     */
    public function testGetNetworkApplianceStaticRoutes()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShaping
     *
     * Display the traffic shaping settings for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShaping()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Return a custom performance class for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingCustomPerformanceClasses
     *
     * List all custom performance classes for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingCustomPerformanceClasses()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingRules
     *
     * Display the traffic shaping settings rules for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingRules()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingUplinkBandwidth
     *
     * Returns the uplink bandwidth settings for your MX network..
     *
     */
    public function testGetNetworkApplianceTrafficShapingUplinkBandwidth()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingUplinkSelection
     *
     * Show uplink selection settings for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingUplinkSelection()
    {
    }

    /**
     * Test case for getNetworkApplianceVlan
     *
     * Return a VLAN.
     *
     */
    public function testGetNetworkApplianceVlan()
    {
    }

    /**
     * Test case for getNetworkApplianceVlans
     *
     * List the VLANs for an MX network.
     *
     */
    public function testGetNetworkApplianceVlans()
    {
    }

    /**
     * Test case for getNetworkApplianceVlansSettings
     *
     * Returns the enabled status of VLANs for the network.
     *
     */
    public function testGetNetworkApplianceVlansSettings()
    {
    }

    /**
     * Test case for getNetworkApplianceVpnBgp
     *
     * Return a Hub BGP Configuration.
     *
     */
    public function testGetNetworkApplianceVpnBgp()
    {
    }

    /**
     * Test case for getNetworkApplianceVpnSiteToSiteVpn
     *
     * Return the site-to-site VPN settings of a network.
     *
     */
    public function testGetNetworkApplianceVpnSiteToSiteVpn()
    {
    }

    /**
     * Test case for getNetworkApplianceWarmSpare
     *
     * Return MX warm spare settings.
     *
     */
    public function testGetNetworkApplianceWarmSpare()
    {
    }

    /**
     * Test case for getOrganizationApplianceSecurityEvents
     *
     * List the security events for an organization.
     *
     */
    public function testGetOrganizationApplianceSecurityEvents()
    {
    }

    /**
     * Test case for getOrganizationApplianceSecurityIntrusion
     *
     * Returns all supported intrusion settings for an organization.
     *
     */
    public function testGetOrganizationApplianceSecurityIntrusion()
    {
    }

    /**
     * Test case for getOrganizationApplianceUplinkStatuses
     *
     * List the uplink status of every Meraki MX and Z series appliances in the organization.
     *
     */
    public function testGetOrganizationApplianceUplinkStatuses()
    {
    }

    /**
     * Test case for getOrganizationApplianceVpnStats
     *
     * Show VPN history stat for networks in an organization.
     *
     */
    public function testGetOrganizationApplianceVpnStats()
    {
    }

    /**
     * Test case for getOrganizationApplianceVpnStatuses
     *
     * Show VPN status for networks in an organization.
     *
     */
    public function testGetOrganizationApplianceVpnStatuses()
    {
    }

    /**
     * Test case for getOrganizationApplianceVpnThirdPartyVPNPeers
     *
     * Return the third party VPN peers for an organization.
     *
     */
    public function testGetOrganizationApplianceVpnThirdPartyVPNPeers()
    {
    }

    /**
     * Test case for getOrganizationApplianceVpnVpnFirewallRules
     *
     * Return the firewall rules for an organization's site-to-site VPN.
     *
     */
    public function testGetOrganizationApplianceVpnVpnFirewallRules()
    {
    }

    /**
     * Test case for swapNetworkApplianceWarmSpare
     *
     * Swap MX primary and warm spare appliances.
     *
     */
    public function testSwapNetworkApplianceWarmSpare()
    {
    }

    /**
     * Test case for updateNetworkApplianceConnectivityMonitoringDestinations
     *
     * Update the connectivity testing destinations for an MX network.
     *
     */
    public function testUpdateNetworkApplianceConnectivityMonitoringDestinations()
    {
    }

    /**
     * Test case for updateNetworkApplianceContentFiltering
     *
     * Update the content filtering settings for an MX network.
     *
     */
    public function testUpdateNetworkApplianceContentFiltering()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallCellularFirewallRules
     *
     * Update the cellular firewall rules of an MX network.
     *
     */
    public function testUpdateNetworkApplianceFirewallCellularFirewallRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallFirewalledService
     *
     * Updates the accessibility settings for the given service ('ICMP', 'web', or 'SNMP').
     *
     */
    public function testUpdateNetworkApplianceFirewallFirewalledService()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallInboundFirewallRules
     *
     * Update the inbound firewall rules of an MX network.
     *
     */
    public function testUpdateNetworkApplianceFirewallInboundFirewallRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallL3FirewallRules
     *
     * Update the L3 firewall rules of an MX network.
     *
     */
    public function testUpdateNetworkApplianceFirewallL3FirewallRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallL7FirewallRules
     *
     * Update the MX L7 firewall rules for an MX network.
     *
     */
    public function testUpdateNetworkApplianceFirewallL7FirewallRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallOneToManyNatRules
     *
     * Set the 1:Many NAT mapping rules for an MX network.
     *
     */
    public function testUpdateNetworkApplianceFirewallOneToManyNatRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallOneToOneNatRules
     *
     * Set the 1:1 NAT mapping rules for an MX network.
     *
     */
    public function testUpdateNetworkApplianceFirewallOneToOneNatRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceFirewallPortForwardingRules
     *
     * Update the port forwarding rules for an MX network.
     *
     */
    public function testUpdateNetworkApplianceFirewallPortForwardingRules()
    {
    }

    /**
     * Test case for updateNetworkAppliancePort
     *
     * Update the per-port VLAN settings for a single MX port..
     *
     */
    public function testUpdateNetworkAppliancePort()
    {
    }

    /**
     * Test case for updateNetworkApplianceSecurityIntrusion
     *
     * Set the supported intrusion settings for an MX network.
     *
     */
    public function testUpdateNetworkApplianceSecurityIntrusion()
    {
    }

    /**
     * Test case for updateNetworkApplianceSecurityMalware
     *
     * Set the supported malware settings for an MX network.
     *
     */
    public function testUpdateNetworkApplianceSecurityMalware()
    {
    }

    /**
     * Test case for updateNetworkApplianceSingleLan
     *
     * Update single LAN configuration.
     *
     */
    public function testUpdateNetworkApplianceSingleLan()
    {
    }

    /**
     * Test case for updateNetworkApplianceStaticRoute
     *
     * Update a static route for an MX or teleworker network.
     *
     */
    public function testUpdateNetworkApplianceStaticRoute()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShaping
     *
     * Update the traffic shaping settings for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShaping()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Update a custom performance class for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingRules
     *
     * Update the traffic shaping settings rules for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingUplinkBandwidth
     *
     * Updates the uplink bandwidth settings for your MX network..
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingUplinkBandwidth()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingUplinkSelection
     *
     * Update uplink selection settings for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingUplinkSelection()
    {
    }

    /**
     * Test case for updateNetworkApplianceVlan
     *
     * Update a VLAN.
     *
     */
    public function testUpdateNetworkApplianceVlan()
    {
    }

    /**
     * Test case for updateNetworkApplianceVlansSettings
     *
     * Enable/Disable VLANs for the given network.
     *
     */
    public function testUpdateNetworkApplianceVlansSettings()
    {
    }

    /**
     * Test case for updateNetworkApplianceVpnBgp
     *
     * Update a Hub BGP Configuration.
     *
     */
    public function testUpdateNetworkApplianceVpnBgp()
    {
    }

    /**
     * Test case for updateNetworkApplianceVpnSiteToSiteVpn
     *
     * Update the site-to-site VPN settings of a network.
     *
     */
    public function testUpdateNetworkApplianceVpnSiteToSiteVpn()
    {
    }

    /**
     * Test case for updateNetworkApplianceWarmSpare
     *
     * Update MX warm spare settings.
     *
     */
    public function testUpdateNetworkApplianceWarmSpare()
    {
    }

    /**
     * Test case for updateOrganizationApplianceSecurityIntrusion
     *
     * Sets supported intrusion settings for an organization.
     *
     */
    public function testUpdateOrganizationApplianceSecurityIntrusion()
    {
    }

    /**
     * Test case for updateOrganizationApplianceVpnThirdPartyVPNPeers
     *
     * Update the third party VPN peers for an organization.
     *
     */
    public function testUpdateOrganizationApplianceVpnThirdPartyVPNPeers()
    {
    }

    /**
     * Test case for updateOrganizationApplianceVpnVpnFirewallRules
     *
     * Update the firewall rules of an organization's site-to-site VPN.
     *
     */
    public function testUpdateOrganizationApplianceVpnVpnFirewallRules()
    {
    }
}
