<?php
/**
 * InterfacesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 27 April, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.0.0-streaming
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * InterfacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InterfacesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDeviceSwitchRoutingInterface
     *
     * Create a layer 3 interface for a switch.
     *
     */
    public function testCreateDeviceSwitchRoutingInterface()
    {
    }

    /**
     * Test case for createNetworkSwitchStackRoutingInterface
     *
     * Create a layer 3 interface for a switch stack.
     *
     */
    public function testCreateNetworkSwitchStackRoutingInterface()
    {
    }

    /**
     * Test case for deleteDeviceSwitchRoutingInterface
     *
     * Delete a layer 3 interface from the switch.
     *
     */
    public function testDeleteDeviceSwitchRoutingInterface()
    {
    }

    /**
     * Test case for deleteNetworkSwitchStackRoutingInterface
     *
     * Delete a layer 3 interface from a switch stack.
     *
     */
    public function testDeleteNetworkSwitchStackRoutingInterface()
    {
    }

    /**
     * Test case for getDeviceSwitchRoutingInterface
     *
     * Return a layer 3 interface for a switch.
     *
     */
    public function testGetDeviceSwitchRoutingInterface()
    {
    }

    /**
     * Test case for getDeviceSwitchRoutingInterfaceDhcp
     *
     * Return a layer 3 interface DHCP configuration for a switch.
     *
     */
    public function testGetDeviceSwitchRoutingInterfaceDhcp()
    {
    }

    /**
     * Test case for getDeviceSwitchRoutingInterfaces
     *
     * List layer 3 interfaces for a switch.
     *
     */
    public function testGetDeviceSwitchRoutingInterfaces()
    {
    }

    /**
     * Test case for getNetworkSwitchStackRoutingInterface
     *
     * Return a layer 3 interface from a switch stack.
     *
     */
    public function testGetNetworkSwitchStackRoutingInterface()
    {
    }

    /**
     * Test case for getNetworkSwitchStackRoutingInterfaceDhcp
     *
     * Return a layer 3 interface DHCP configuration for a switch stack.
     *
     */
    public function testGetNetworkSwitchStackRoutingInterfaceDhcp()
    {
    }

    /**
     * Test case for getNetworkSwitchStackRoutingInterfaces
     *
     * List layer 3 interfaces for a switch stack.
     *
     */
    public function testGetNetworkSwitchStackRoutingInterfaces()
    {
    }

    /**
     * Test case for updateDeviceSwitchRoutingInterface
     *
     * Update a layer 3 interface for a switch.
     *
     */
    public function testUpdateDeviceSwitchRoutingInterface()
    {
    }

    /**
     * Test case for updateDeviceSwitchRoutingInterfaceDhcp
     *
     * Update a layer 3 interface DHCP configuration for a switch.
     *
     */
    public function testUpdateDeviceSwitchRoutingInterfaceDhcp()
    {
    }

    /**
     * Test case for updateNetworkSwitchStackRoutingInterface
     *
     * Update a layer 3 interface for a switch stack.
     *
     */
    public function testUpdateNetworkSwitchStackRoutingInterface()
    {
    }

    /**
     * Test case for updateNetworkSwitchStackRoutingInterfaceDhcp
     *
     * Update a layer 3 interface DHCP configuration for a switch stack.
     *
     */
    public function testUpdateNetworkSwitchStackRoutingInterfaceDhcp()
    {
    }
}
