<?php
/**
 * TrafficShapingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Meraki Dashboard API
 *
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 27 April, 2021 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 1.0.0-streaming
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TrafficShapingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TrafficShapingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Add a custom performance class for an MX network.
     *
     */
    public function testCreateNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for deleteNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Delete a custom performance class from an MX network.
     *
     */
    public function testDeleteNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShaping
     *
     * Display the traffic shaping settings for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShaping()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Return a custom performance class for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingCustomPerformanceClasses
     *
     * List all custom performance classes for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingCustomPerformanceClasses()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingRules
     *
     * Display the traffic shaping settings rules for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingRules()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingUplinkBandwidth
     *
     * Returns the uplink bandwidth settings for your MX network..
     *
     */
    public function testGetNetworkApplianceTrafficShapingUplinkBandwidth()
    {
    }

    /**
     * Test case for getNetworkApplianceTrafficShapingUplinkSelection
     *
     * Show uplink selection settings for an MX network.
     *
     */
    public function testGetNetworkApplianceTrafficShapingUplinkSelection()
    {
    }

    /**
     * Test case for getNetworkTrafficShapingApplicationCategories
     *
     * Returns the application categories for traffic shaping rules..
     *
     */
    public function testGetNetworkTrafficShapingApplicationCategories()
    {
    }

    /**
     * Test case for getNetworkTrafficShapingDscpTaggingOptions
     *
     * Returns the available DSCP tagging options for your traffic shaping rules..
     *
     */
    public function testGetNetworkTrafficShapingDscpTaggingOptions()
    {
    }

    /**
     * Test case for getNetworkWirelessSsidTrafficShapingRules
     *
     * Display the traffic shaping settings for a SSID on an MR network.
     *
     */
    public function testGetNetworkWirelessSsidTrafficShapingRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShaping
     *
     * Update the traffic shaping settings for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShaping()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingCustomPerformanceClass
     *
     * Update a custom performance class for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingCustomPerformanceClass()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingRules
     *
     * Update the traffic shaping settings rules for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingRules()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingUplinkBandwidth
     *
     * Updates the uplink bandwidth settings for your MX network..
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingUplinkBandwidth()
    {
    }

    /**
     * Test case for updateNetworkApplianceTrafficShapingUplinkSelection
     *
     * Update uplink selection settings for an MX network.
     *
     */
    public function testUpdateNetworkApplianceTrafficShapingUplinkSelection()
    {
    }

    /**
     * Test case for updateNetworkWirelessSsidTrafficShapingRules
     *
     * Update the traffic shaping settings for an SSID on an MR network.
     *
     */
    public function testUpdateNetworkWirelessSsidTrafficShapingRules()
    {
    }
}
